- hosts: localhost
  tasks:
    ### Libvirt Prometheus Exporter
    - name: Install dependencies
      apt:
        name: ["python3-pip", "python3-libvirt", "systemd-container", "sysstat"]
        state: present
      tags: install

    - name: Check pip3 local path
      stat:
        path: /usr/local/bin/pip3
      register: pip3_local
      tags: install

    - name: Install prometheus_client
      pip:
        name: prometheus_client
        state: present
        executable: /usr/local/bin/pip3
      register: prom_c
      when: pip3_local.stat.exists
      tags: install

    - name: Install prometheus_client
      pip:
        name: prometheus_client
        state: present
        executable: /usr/bin/pip3
      register: prom_c
      when: pip3_local.stat.exists == false
      tags: install

    - name: Create libvirt exporter directory
      file:
        path: /opt/libvirt_exporter
        state: directory
        mode: '0755'
      tags: install

    - name: Place libvirt metadata manager
      copy:
        src: libvirtmetadata.py
        dest: /opt/libvirt_exporter/libvirtmetadata.py
      register: lm
      tags: install

    - name: Place task scheduler
      copy:
        src: scheduler.py
        dest: /opt/libvirt_exporter/scheduler.py
      register: ts
      tags: install

    - name: Place libvirt exporter
      copy:
        src: libvirt_exporter.py
        dest: /opt/libvirt_exporter/libvirt_exporter.py
      register: exporter
      tags: install

    - name: Render libvirt_exporter service template
      template:
        src: libvirt_exporter.service.j2
        dest: /etc/systemd/system/libvirt_exporter.service
        mode: 0644
      register: service
      tags: install

    - name: Restart and assure enabled libvirt_exporter
      systemd:
        name: libvirt_exporter
        state: restarted
        enabled: yes
        daemon-reload: "{{ service.changed }}"
      register: service_restart
      when: exporter.changed or lm.changed or ts.changed or prom_c.changed or service.changed
      tags: install

    - name: Start and enable libvirt_exporter
      systemd:
        name: libvirt_exporter
        state: started
        enabled: yes
      when: service_restart is skipped
      tags: install

    - name: Stop and disable libvirt_exporter
      systemd:
        name: libvirt_exporter
        state: stopped
        enabled: no
      tags: never, uninstall
